name: "Cached LFS checkout (Google Drive)"

description: "Git checkout with LFS files from cache using Google Drive"

branding:
  icon: "download"
  color: "green"

inputs:
  include:
    description: "Explicitly include files for LFS"
    required: false
    default: "*"
  exclude:
    description: "Explicitly exclude files for LFS"
    required: false
    default: ""
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all tags and branches"
    required: false
    default: 1
  clean:
    description: "Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching"
    required: false
    default: true
  filter:
    description: >
      Partially clone against a given filter.
      Overrides sparse-checkout if set.
    default: ""
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
    required: false
    default: ""
  repository:
    description: "Repository name with owner. For example, actions/checkout"
    default: ${{ github.repository }}
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
  submodules:
    description: >
      Whether to checkout submodules: `true` to checkout submodules or `recursive` to
      recursively checkout submodules.
    required: false
    default: false
  persist-credentials:
    description: >
      'Whether to configure the token or SSH key with the local git config'
    required: false
    default: true
  googleServiceAccountCredentialsJSON:
    description: "The JSON contents of the Google Service Account credentials file"
    required: true
  googleDriveFolderID:
    description: "The ID of the Google Drive folder to use for caching"
    required: true
  mainBranchRefName:
    description: "The name of the main branch"
    required: false
    default: "main"
  restoreOnly:
    description: "Only restore the cache, do not save the cache"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        submodules: ${{ inputs.submodules }}
        persist-credentials: ${{ inputs.persist-credentials }}
        filter: ${{ inputs.filter }}
        clean: ${{ inputs.clean }}

    - name: Create LFS file list
      run: |
        {
          git lfs ls-files --long --include "${{ inputs.include }}" --exclude "${{ inputs.exclude }}"
          git submodule foreach --quiet git lfs ls-files --long --include "${{ inputs.include }}" --exclude "${{ inputs.exclude }}"
        } | cut -d ' ' -f1 | sort -u > .lfs-assets-id
      shell: bash

    - name: Create Submodule LFS Cache Paths
      id: cache-paths
      run: |
        CACHE_PATHS=""

        # loop over the git submodule paths to generate a list of module directories to cache
        # `git config` is used to extract the `path` value for each git submodule
        # for more information about the .gitmodules file, see: https://git-scm.com/docs/gitmodules
        if [ -f .gitmodules ]; then
          while read -r line; do
            CACHE_PATHS+=".git/modules/$line/lfs "
          done < <(git config --file .gitmodules --get-regexp path | awk '{ print $2 }')
        fi

        echo "CACHE_PATHS=$CACHE_PATHS" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Compute Cache Parameters
      id: cache-params
      run: |
        {
          echo "path<<EOF"
          echo ".git/lfs"
          if [ -n "${{ steps.cache-paths.outputs.CACHE_PATHS }}" ]; then
            echo "${{ steps.cache-paths.outputs.CACHE_PATHS }}"
          fi
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        echo "key=lfs-v4-${{ inputs.repository }}-${{ github.ref_name }}-${{ hashFiles('.lfs-assets-id') }}" >> "$GITHUB_OUTPUT"

        {
          echo "restore-keys<<EOF"
          echo "lfs-v4-${{ inputs.repository }}-${{ github.ref_name }}-"
          echo "lfs-v4-${{ inputs.repository }}-${{ inputs.mainBranchRefName }}-"
          echo "lfs-v4-${{ inputs.repository }}-"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Restore LFS cache from Google Drive
      uses: madrona-games/google-drive-actions/cache@v2
      if: inputs.restoreOnly == 'false'
      with:
        path: ${{ steps.cache-params.outputs.path }}
        key: ${{ steps.cache-params.outputs.key }}
        restore-keys: ${{ steps.cache-params.outputs.restore-keys }}
        google-service-account-credentials-json: ${{ inputs.googleServiceAccountCredentialsJSON }}
        google-drive-folder-id: ${{ inputs.googleDriveFolderID }}

    - name: Restore Only LFS cache from Google Drive
      uses: madrona-games/google-drive-actions/cache/restore@v2
      if: inputs.restoreOnly == 'true'
      with:
        path: ${{ steps.cache-params.outputs.path }}
        key: ${{ steps.cache-params.outputs.key }}
        restore-keys: ${{ steps.cache-params.outputs.restore-keys }}
        google-service-account-credentials-json: ${{ inputs.googleServiceAccountCredentialsJSON }}
        google-drive-folder-id: ${{ inputs.googleDriveFolderID }}

    - name: Git LFS Pull
      run: |
        git lfs pull --include "${{ inputs.include }}" --exclude "${{ inputs.exclude }}"
        git submodule foreach --quiet git lfs pull --include "${{ inputs.include }}" --exclude "${{ inputs.exclude }}"
        git lfs prune
        git submodule foreach git lfs prune
      shell: bash

    # Don't leave behind temp files in case build system checks for dirty workspace
    - name: Clean up temp files
      if: always()
      run: rm .lfs-assets-id
      shell: bash
