name: "S3 Cache Provider"
description: "Cache LFS files using S3-compatible storage"

inputs:
  path:
    description: "The paths to cache"
    required: true
  key:
    description: "The cache key"
    required: true
  restore-keys:
    description: "The restore keys"
    required: true
  restoreOnly:
    description: "Only restore the cache, do not save the cache"
    required: false
    default: false
  endpoint:
    description: "The URL of the S3 bucket to use for caching"
    required: true
  port:
    description: "The port of the S3 bucket to use for caching"
    required: false
  accessKey:
    description: "The access key for the S3 bucket"
    required: true
  secretKey:
    description: "The secret key for the S3 bucket"
    required: true
  bucket:
    description: "The name of the S3 bucket to use for caching"
    required: true
  insecure:
    description: "Whether to use insecure S3 connections"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Restore LFS cache from S3
      if: inputs.restoreOnly == 'false'
      uses: madrona-games/s3-actions-cache@v2
      with:
        endpoint: ${{ inputs.endpoint }}
        port: ${{ inputs.port }}
        accessKey: ${{ inputs.accessKey }}
        secretKey: ${{ inputs.secretKey }}
        bucket: ${{ inputs.bucket }}
        insecure: ${{ inputs.insecure }}
        use-fallback: false
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}

    - name: Restore Only LFS cache from S3
      if: inputs.restoreOnly == 'true'
      uses: madrona-games/s3-actions-cache/restore@v2
      with:
        endpoint: ${{ inputs.endpoint }}
        port: ${{ inputs.port }}
        accessKey: ${{ inputs.accessKey }}
        secretKey: ${{ inputs.secretKey }}
        bucket: ${{ inputs.bucket }}
        insecure: ${{ inputs.insecure }}
        use-fallback: false
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
